#!/usr/bin/env bash

THIS_DIR=$(dirname "$(readlink -f "$0")")

clone() {
    commit=$1 && shift
    url=$1 && shift
    dest=$1 && shift

    group_name=$(basename "$(dirname "$url")")
    repo_name=$(basename "$url")
    target="$THIS_DIR/cache/submodules/$group_name/$repo_name"

    git clone "$@" --single-branch "$url" "$target"
    git -C "$target" checkout "$commit"
    ln -sfv --relative -T "$target" "$dest"
}

clone master https://github.com/jocelynmallon/zshmarks ~/.zshine/plugins/zshmarks
clone master https://github.com/zsh-users/zsh-history-substring-search ~/.zshine/plugins/zsh-history-substring-search
clone 0.17.5 https://github.com/junegunn/fzf ~/.zshine/plugins/fzf
clone master https://github.com/lcpz/lain ~/.config/awesome/lain
clone v1.24 https://github.com/zdharma/fast-syntax-highlighting ~/.zshine/plugins/fast-syntax-highlighting
