#!/usr/bin/env python3

from pathlib import Path
import re
import os
import sys
import time

# firefox only supports .5 steps
DPIS = [96, 144, 192]


def set_dpi(dpi):
    # prepare
    os.system(f"sed --follow-symlinks -i 's|^Xft.dpi: .*|Xft.dpi: {dpi}|' ~/.Xresources")
    os.system("cp /usr/share/applications/spotify.desktop ~/.local/share/applications/")
    os.system(f"sed -i 's|Exec=spotify .*|Exec=spotify --force-device-scale-factor={dpi/96} %U|' ~/.local/share/applications/spotify.desktop")

    # apply changes
    os.system("xrdb -merge ~/.Xresources")
    os.system("echo 'awesome.restart()' | awesome-client")
    time.sleep(0.2)
    os.system(f"notify-send dpitog 'switched to DPI = {dpi}'")


current_dpi = None
with open(Path.home() / ".Xresources", 'r') as f:
    match = re.findall(r'^Xft.dpi:\s+(\d+)$', f.read(), re.MULTILINE)
    current_dpi = int(match[0]) if 0 < len(match) else 0

for dpi in sorted(DPIS):
    if dpi > current_dpi:
        set_dpi(dpi)
        sys.exit(0)

set_dpi(DPIS[0])
