#!/usr/bin/env bash

name=${0/$HOME/\~}

pids=$(pidof compton)
if [[ $? -eq 1 ]]; then
    compton &
    notify-send "$name" "compton enabled"
else
    kill $pids
    notify-send "$name" "compton disabled"
fi
