#!/usr/bin/env bash

HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoreboth:erasedups  # don't put duplicate lines or lines starting with whitespace in history
shopt -s histappend  # append history instead of overwrite
shopt -s cmdhist  # store multiline commands in a single entry
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"  # write history immediately

shopt -s globstar 2> /dev/null  # ** to glob recursive

is_cmd() { command -v "$1" > /dev/null 2>&1; }

is_cmd nvim && alias vim=nvim

is_cmd vi    && export EDITOR=vi
is_cmd vim   && export EDITOR=vim
is_cmd nvim  && export EDITOR=nvim
is_cmd gls  && ls() { gls "$@"; }
is_cmd dircolors && eval "$(dircolors -b)"

PROMPT_COMMAND=_prompt
_prompt() {
    local EXIT="$?"

    local reset='\[\e[0m\]'
    local red='\[\e[1;31m\]'
    local green='\[\e[1;32m\]'
    local yellow='\[\e[1;33m\]'
    local blue='\[\e[1;34m\]'
    local magenta='\[\e[1;35m\]'

    [[ -n "$SSH_CONNECTION" ]] && local PREFIX="${magenta}[SSH] ${reset}"

    user_color=$blue
    [ $UID = 0 ] && user_color=$red
    PS1="\n${reset}${PREFIX}${user_color}\u${green}@\h ${yellow}\w "

    if [ $EXIT != 0 ]; then
        PS1+="${red}$EXIT ${reset}\$ "
    else
        PS1+="${reset}\$ "
    fi
}

# up/down for history search
if [[ $- == *i* ]]; then
    bind '"\e[A": history-search-backward'
    bind '"\e[B": history-search-forward'
fi

export CLICOLOR='1'

### color man pages
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[1;94m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[2m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[1;92m' \
    man "$@"
}

### security aliases
alias cp='cp -i'
alias mv='mv -i'
alias ln='ln -i'

### convenience aliases
alias ls='ls -Fhl  --color=auto'
alias la='ls -FhlA --color=auto'
alias ll='ls -Fhl  --color=auto'
alias rd='rmdir'
alias mkdir='mkdir -p'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias grep='grep --color=auto'

[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases

true
