#!/usr/bin/env bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        source "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

setxkbmap -option caps:escape  # remap caps to escape
xset r rate 200 30  # faster keyboard repeat

# make some cache persistent, some in tmpfs
rm -f ~/.cache && ln -s /tmp ~/.cache
mkdir -p ~/.local/share/yay && ln -sfn ~/.local/share/yay ~/.cache/yay
mkdir -p ~/.local/share/keepassxc && ln -sfn ~/.local/share/keepassxc ~/.cache/keepassxc
mkdir -p ~/.local/share/thumbnails && ln -sfn ~/.local/share/thumbnails ~/.cache/thumbnails
mkdir -p ~/.local/share/thumbnails/darktable && ln -sfn ~/.local/share/thumbnails/darktable ~/.cache/darktable

# the location ~/.local/share/applications is deprecated for mimeapps.list but it gets still used sometimes, so make sure they are the same
mkdir -p ~/.local/share/applications
ln -sf ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list
ln -sf ~/.config/mimeapps.list ~/.local/share/applications/defaults.list


# applications
window_manager=awesome
nitrogen --restore &
lxpolkit &
picom &
[[ $HOSTNAME == x1 ]] && xcalib ~/.config/x1carbon3rd_notebookcheck.com.icc &
redshift &
dunst &
~/.bin/workstats &
start-pulseaudio-x11 &
bash -c "if $HOME/.bin/wait-for-host dropbox.com; then dropbox; fi" &

# parcellite simple mode: do not do anything except keep clipboard of closed applications (no history etc.)
mkdir -p ~/.config/parcellite
cat << EOF > ~/.config/parcellite/parcelliterc
[rc]
RCVersion=1
use_copy=true
save_history=false
restore_empty=true
menu_key=
history_key=
phistory_key=
actions_key=
EOF
parcellite --no-icon &

if [[ $HOSTNAME == x1 || $HOSTNAME == dell ]]; then
    # dim after 2min, lock after 3min
    xset s 120 60
    xss-lock -l -n ~/.bin/dim -- ~/.bin/lock &

    # turn off display after 5m
    xset dpms 300 300 300
fi

if [[ $HOSTNAME == desk ]]; then
    # soft-lock (close keepass etc.) after 3min
    xset s 180
    xss-lock -l -- ~/.bin/lock soft &

    # turn off display after 30m
    xset dpms 1800 1800 1800

    solaar --restart-on-wake-up --window hide &
    numlockx on &
    pulseeffects --gapplication-service &

    if ! mount | grep -q "root@srv1.home:/media/data"; then
        bash -c "$HOME/.bin/wait-for-host srv1.home && sshfs root@srv1.home:/media/data /media/data -o reconnect -o BatchMode=yes -o allow_other" &
    fi

    cat << 'EOF' | bash &
    set -e
    PATH=$HOME/.bin:$PATH

    wait-for-host spotify.com
    pidof spotify || exo-open "$HOME/.local/share/applications/spotify.desktop"
    xdotool set_desktop_for_window "$(xdotool search --limit 1 --sync --name "^Spotify Premium$")" 5

    # for ddcutil (brightness control)
    sudo modprobe i2c-dev &
EOF

    cat << 'EOF' | bash &
    set -e
    PATH=$HOME/.bin:$PATH

    wait-for-host srv1.home
    pidof kodi-x11 || exo-open "/usr/share/applications/kodi.desktop"
    xdotool set_desktop_for_window "$(xdotool search --limit 1 --sync --class "kodi")" 6
EOF

fi

exec "$window_manager"
