#!/usr/bin/env bash

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        source "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

if [[ $HOSTNAME == x1 ]]; then
    xrandr --output eDP --mode 3072x1920 --rate 120 &
    blueman-applet &
    pactl set-sink-mute @DEFAULT_SINK@ true &
    yubikey-touch-detector --libnotify &
    ~/.bin/x1/track-battery &
fi

if [[ $HOSTNAME == desk ]]; then
    xrandr --output DP-1 --mode 2560x1440 --auto --primary --rate 69.93
    xrandr --output DisplayPort-0 --mode 2560x1440 --auto --primary --rate 69.93
    xrandr --output HDMI-1 --off
    xrandr --output HDMI-A-0 --off
fi

# make some cache persistent, some in tmpfs
if [[ "$(findmnt -no fstype -T /tmp)" == tmpfs ]]; then
    rm -f ~/.cache && ln -s "/tmp/$UID" ~/.cache
    mkdir -p ~/.local/share/ansible-lint && ln -sfn ~/.local/share/ansible-lint ~/.cache/ansible-lint
    mkdir -p ~/.local/share/yay && ln -sfn ~/.local/share/yay ~/.cache/yay
    mkdir -p ~/.local/share/keepassxc && ln -sfn ~/.local/share/keepassxc ~/.cache/keepassxc
    mkdir -p ~/.local/share/thumbnails && ln -sfn ~/.local/share/thumbnails ~/.cache/thumbnails
    mkdir -p ~/.local/share/thumbnails/darktable && ln -sfn ~/.local/share/thumbnails/darktable ~/.cache/darktable
fi

# cleanup history
rm -rf ~/.local/share/recently-used.xbel ~/.local/share/RecentDocuments
echo -n > ~/.local/share/recently-used.xbel
sudo chattr +i ~/.local/share/recently-used.xbel
mkdir -p ~/.local/share/RecentDocuments
sudo chattr +i ~/.local/share/RecentDocuments

# the location ~/.local/share/applications is deprecated for mimeapps.list but it gets still used sometimes, so make sure they are the same
mkdir -p ~/.local/share/applications
ln -sf ~/.config/mimeapps.list ~/.local/share/applications/mimeapps.list
ln -sf ~/.config/mimeapps.list ~/.local/share/applications/defaults.list

# applications
opensnitch-ui &
nitrogen --restore &
lxpolkit &
picom &
redshift-gtk &
dunst &
keepassxc &
bash -c "if $HOME/.bin/wait-for-host dropbox.com; then dropbox; fi" &

~/.bin/xinitrc/setup-lock &

# parcellite simple mode: do not do anything except keep clipboard of closed applications (no history etc.)
mkdir -p ~/.config/parcellite
cat << EOF > ~/.config/parcellite/parcelliterc
[rc]
RCVersion=1
use_copy=true
save_history=false
restore_empty=true
EOF
parcellite --no-icon &

if [[ $HOSTNAME == x1 ]]; then
    usbguard-notifier --wait &
    cbatticon &
    nm-applet &
fi

if [[ $HOSTNAME == desk ]]; then
    solaar --restart-on-wake-up --window hide &
    numlockx on &
    easyeffects --gapplication-service &

    # for ddcutil (brightness control)
    sudo modprobe i2c-dev &

    cat << 'EOF' | bash &
    set -e
    PATH=$HOME/.bin:$PATH
    pidof portfolio || exo-open /usr/share/applications/portfolio-performance-bin.desktop
    sleep 5
    timeout 10 xdotool search --sync --class "Portfolio Performance" | xargs -I {} xdotool set_desktop_for_window {} 5
EOF
fi


cat << 'EOF' | bash &
TRIES=0
while true; do
    let TRIES++
    if ((TRIES > 30)); then
        exit 0
    else
        setxkbmap -option caps:escape  # remap caps to escape
        xset r rate 200 30  # faster keyboard repeat
    fi
    sleep 0.5
done
EOF

exec awesome
