# start redshift in oneshot DRM mode (works in tty)
[[ "$commands[redshift]" ]] && redshift -o -m drm

if [[ -n "$commands[startx]" ]]; then
    [[ -z "$DISPLAY" && "$XDG_VTNR" == 1 && "$USER" != root ]] && startx
fi
