#!/usr/bin/env bash

discharge=$(</sys/class/power_supply/BAT0/power_now)
discharge=$(awk -v d="$discharge" 'BEGIN { printf "%.2f", d/1000000 }')

printf '%s\n' "<span foreground='#ffff00'>Battery:</span>$(acpi -b | cut -d: -f 2-)"
printf '%s\n' "<span foreground='#ffff00'>Discharge:</span> $discharge W"
