#!/usr/bin/env bash

set -eu

color02=#A9A9A9
color31=#ff0000
color32=#00ff00
color33=#ffff00

convert_colors() {
    perl -pe "
    s/\x1b\[31m/<span foreground=\'$color31\'>/g;
    s/\x1b\[32m/<span foreground=\'$color32\'>/g;
    s/\x1b\[33m/<span foreground=\'$color33\'>/g;
    s/\x1b\[2m/<span foreground=\'$color02\'>/g;
    s/\x1b\[0m/<\/span>/g;
    "
}

out=$(nmcli --color=yes -t)
printf '%s\n' "$out" | head -n -5 | convert_colors

