#!/usr/bin/env bash

out_general=$(nmcli --color=yes general status)
out_active=$(nmcli --color=yes -f name,type,device connection show --active)

active_dev=$(nmcli -t -f device connection show --active)
out_device=$(nmcli -e yes -t --color=yes device show wlan0 | grep -v GENERAL.CON-PATH | sed 's/:/|/' | column -t -s\|)

color31="#ff0000"
color32="#00ff00"
color33="#ffff00"

echo -e "$out_general\n\n$out_active\n\n$out_device" |
    perl -pe "
    s/\x1b\[31m/<span foreground=\'$color31\'>/g;
    s/\x1b\[32m/<span foreground=\'$color32\'>/g;
    s/\x1b\[33m/<span foreground=\'$color33\'>/g;
    s/\x1b\[0m/<\/span>/g
    "
