#!/usr/bin/env bash

set -eu

is_active_tmux() {
    tmux ls >/dev/null 2>&1
}
is_active_ssh() {
    ss | grep ':ssh\s' > /dev/null
}
is_active_x11() {
    idle_milliseconds=$(DISPLAY=:0 xprintidle)
    limit=$((1000 * 60 * 10))  # 10min
    [[ "$idle_milliseconds" -lt "$limit" ]]
}
is_active_audio() {
    pactl list | grep 'State:\s' | grep 'RUNNING' > /dev/null
}

die() {
    printf '%s\n' "WARNING: $1 is still active!"
    rc=1
}

rc=0
is_active_tmux && die "tmux"
is_active_ssh && die "ssh"
is_active_x11 && die "x11"
is_active_audio && die "audio"

if [[ "$rc" == 0 ]]; then
    systemctl suspend
fi

exit 0
