project:
  render: ["/*.md"]
  output-dir: .output

lang: en

toc: true
number-sections: false
# number-depth: 2

filters:
  - compact-list
  - ascii-replacer

format:
  # https://quarto.org/docs/reference/formats/pdf.html
  # https://quarto.org/docs/output-formats/pdf-basics.html
  pdf:
    hyperrefoptions:
      - linktoc=all  # also link page numbers in TOC
    documentclass: scrbook  # scrbook (based on book, e.g. only start chapters on new pages), scrartcl (based on article)
    classoption:
      - oneside  # default: twoside for scrbook
      - headsepline=true  # show separator under header

      # optional
      # - headings=standardclasses  # serif headings
      # - afterindent=false
      # - chapterprefix=false
    papersize: a4
    pdf-engine: lualatex
    fontsize: 11pt  # rM2: 14pt
    geometry: [top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm, heightrounded]
    # rM2: [top=1cm, bottom=1cm, left=1.5cm, right=1cm, heightrounded]
    colorlinks: true
    links-as-notes: true
    csquotes: true  # localized quotation marks
    mainfont: Erewhon
    mathfont: Erewhon-Math
    include-in-header:
      # wrap code
      - text: |
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

      # better than builtin "-V linestretch", because it also affects TOC
      - text: |
          \usepackage{setspace}\setstretch{1.25}

      # reduce spacing above chapter
      - text: |
          \ifdefined\chapter
          \RedeclareSectionCommand[beforeskip=-1sp]{chapter}
          \fi

      # make section headers bigger
      - text: |
          \ifdefined\chapter
          \addtokomafont{chapterprefix}{\Huge}
          \fi
          \RedeclareSectionCommand[font=\LARGE]{section}
          \RedeclareSectionCommand[font=\Large]{subsection}
          \RedeclareSectionCommand[font=\large]{subsubsection}

      # better bullet points after 2nd level
      - text: |
          \usepackage{enumitem}
          \setlist[itemize,3]{label=$\circ$}
          \setlist[itemize,4]{label=$\circ$}
          \setlist[itemize,5]{label=$\circ$}

      # rotate pages with \blandscape/\elandscape
      - text: |
          \usepackage{pdflscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}

  # https://quarto.org/docs/reference/formats/html.html
  # https://quarto.org/docs/output-formats/html-basics.html
  html:
    embed-resources: true

    # 'mathml' looks better in Firefox, needs no dependencies
    # 'mathjax': looks more like LaTeX (serif) and looks better in Chrome, has JS CDN dependency
    # 'katex' similar to mathjax, but faster (?)
    # 'plain' also works well usually (utf8 symbols, no dependencies)
    html-math-method: mathml
    theme: default  # alternative (lighter fonts): lumen

  # https://quarto.org/docs/reference/formats/markdown/commonmark.html
  # renders more nicely than pandoc markdown
  commonmark_x:
    toc: false
    wrap: preserve

format-links: false
